### ISSUE TITLE
Use native igraph object as ground truth

### ISSUE THREAD

**Issue by krlmlr** [igraph/rigraph#787]
## Converting from R to C

- No work needs to be done, the native igraph object is stored as an external pointer in the `igraph_t_idx_env` part of the data structure.
- When the R graph object is destroyed, it will be garbage-collected eventually. This triggers the finalizer of the external pointer object, which can be made to call destructors in igraph/C.

## Converting from C to R

- We keep the native `igraph_t` object and store it as an external pointer in the `igraph_t_idx_env` part of the data structure.
- We also keep all the information needed to recreate the native `igraph_t` object in the `igraph_t_idx_n`, `igraph_t_idx_directed`, `igraph_t_idx_from` and `igraph_t_idx_to` components
- The native `igraph_t` object may be lost, e.g., during serialization. In this case, we recreate the native `igraph_t` object from the `igraph_t_idx_n`, `igraph_t_idx_directed`, `igraph_t_idx_from` and `igraph_t_idx_to` components

## Attributes

All attributes are still handled only from R for now. ~~But because the native `igraph_t` object may cache R-level attributes, we need to be especially careful about this.~~

## Implementation steps

- [x] Ensure that all indices into `unclass(g)` use `igraph_t_idx_*`, no magic numbers (#784)
- [ ] Fix problems in #789
    - This PR contains the results from checking all reverse dependencies against 6222e73a6. This is the commit where all indexes in the internal list have been shifted. It seems like our code (or perhaps even other packages) are relying on those indexes. We need to understand what causes the failures, and fix them.
- [x] Implement accessors (getters + setters) for `igraph_t_idx_n`, `igraph_t_idx_directed`, `igraph_t_idx_from` and `igraph_t_idx_to` in C
- [x] Don't use `igraph_t_idx_*` from R, at all (we can keep using `igraph_attr_idx_*`)
    - create R wrappers for accessors from previous step if needed
- [x] Store native `igraph_t` as external pointer in `igraph_t_idx_env`
    - the native `igraph_t` is an external pointer stored in `unclass(graph)[[igraph_t_idx_env]]$igraph`
- [x] Rewrite C-level accessors to refer to native `igraph_t`
    - fallback to recreating native `igraph_t` from `igraph_t_idx_n`, `igraph_t_idx_directed`, `igraph_t_idx_from` and `igraph_t_idx_to` if the external pointer is gone
    - use `unserialize(serialize(graph, NULL))` to test
- [x] Avoid populating `igraph_t_idx_oi`...`igraph_t_idx_is` in R
- [x] Implement ALTREP for `igraph_t_idx_from` and `igraph_t_idx_to` (requires R 4.0)
- [ ] Double-check immutability (`INOUT` in `functions.yaml`)
- [ ] Double-check attribute handling

Follow-up to #783.

**Comment by krlmlr** [comment]
Yes, they're no longer needed there.

**Comment by Antonov548** [comment]
> Yes, they're no longer needed there.

Should graph members `igraph_t_idx_oi...igraph_t_idx_is` restored from pointer to igraph in environment? 
If yes, how this members should be restored if there is no environment or pointer?

**Comment by krlmlr** [comment]
@ntamas @szhorvat: Can you please help? I remember hearing that the `igraph_t_idx_oi...igraph_t_idx_is` components are redundant and perhaps computed on demand. Do they need to be computed actively, or are they populated "as needed"?

**Comment by szhorvat** [comment]
Every part of `igraph_t`, except the cache, must be complete.  They are not computed lazily.

The proper way to create an `igraph_t` is through `igraph_create()`. For this you need a contiguously stored edge list, i.e. not separate list of sources and targets, but a single vector in the format `source1, target1, source2, target2, ...` This is why I suggested that on the R side we also shouldn't store two separate sources and targets vectors, but one standard format edge list.

Internally, `igraph_create()` is simply calling `igraph_empty()`, `igraph_add_vertices()` and `igraph_add_edges()`. However, these three functions are not trivial, and re-implementing parts of them on the R side should be avoided. They are part of igraph's core which we aim to keep opaque, isolated from the rest of the library, and having a very small API surface.

Thus I still think that the best way to proceed here is to avoid manipulating the innards of `igraph_t` from R/igraph as much as possible (except for attributes). Just store the edge list on the R side, if at all possible in the standard format (flat vector), then use `igraph_create()` to reconstruct the `igraph_t` when needed and plug in the attributes manually.

**Comment by krlmlr** [comment]
I think we should keep the current layout of the R data structure, for compatibility.

IIUC this means that if the native `igraph_t` is missing in the R environment, we call `igraph_create()` with suitably prepared input.

**Comment by szhorvat** [comment]
I wanted to keep the above simple, so I suggested `igraph_create()`, which will work fine. But there may be a small safety advantage in using a sequence of `igraph_empty()`, `igraph_add_vertices()` and `igraph_add_edges()` instead. This will throw an error if the edges vector contains vertex IDs which are too large (e.g. because the data got corrupted on the R side). `igraph_create()` will just auto-create the missing vertices.

For reference, here's how to expand out an `igraph_create()` into these three steps:

```
igraph_create(&graph, edges, n, directed);
```

is equivalent to

```
igraph_empty(&graph, n, directed);
igraph_add_edges(&graph, edges, NULL);
```

but the latter has stricter error checking.

**Comment by Antonov548** [comment]
@krlmlr Just to clarify: Altrep is needed just for `from`, `to` members printing purpose?

**Comment by krlmlr** [comment]
For serialization of the igraph object at the R level. We want ALTREP to avoid materializing `from` and `to` eagerly.

**Comment by krlmlr** [comment]
It looks like we need to implement only `R_altvec_Dataptr_or_null_method_t` or `R_altvec_Dataptr_method_t`, and `R_altrep_Length_method_t` . Everything else can be omitted.

The data should be returned as an array of `REAL`, for compatibility. This means that we need to copy, perhaps we allocate a `REAL` vector and store it in the second ALTREP data component `R_altrep_data2()` . The first ALTREP data component `R_altrep_data1()` can store the environment that contains the `igraph` as an external pointer.

**Comment by krlmlr** [comment]
This is done now, with the 1.5.0 release.
