### ISSUE TITLE
0.10 functions that should be exposed

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#912]
## Priority 0

This is a list of functions that are new in 0.10 and should probably be exposed in the very first R/igraph release based on 0.10. Should be easy through auto-generation. The `igraph_` part is omitted from function names.

 - [x] `is_forest` and `is_acyclic`
 - [ ] `has_mutual` -> `any_mutual`
 - [ ] `invalidate_cache` — we need this for debugging
 - [ ] ... ?

## Priority 1

These would be nice to expose _soon_ though perhaps not in the first release. Several of these were requested by users. Auto-generation is not always possible.

 - [ ] `hub_and_authority_scores` to replace separate hub and authority score calculation
 - [x] `get_k_shortest_paths` #972 
 - [ ]  `graph_center`
 - [ ] ... ?

Add support for extra features  to existing functions. These are often a separate function in C, but should be integrated into the same function in R.

 - [ ] `radius_dijkstra` and `eccentricity_dijkstra` (i.e. weight support for both, #893)
 - [ ] `distances_cutoff` (cutoff support)
 - [ ] ... ?

Generators (probably all of these can be auto-generated):

 - [ ] `circulant`
 - [ ] `turan`
 - [ ] `wheel`
 - [ ] `full_multipartite`
 - [ ] `regular_tree`
 - [ ] `symmetric_tree`
 - [ ] `triangular_lattice`
 - [ ] `hexagonal_lattice`
 - [ ] `generalized_petersen`
 - [ ] ... ?
